name: Build and Test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Break Build for branch 'renovate/major-quarkus*'
        if: contains(github.ref, 'renovate/major-quarkus')
        run: mvn -B install '-Dtest=FailingTest' --file pom.xml

      - name: Build (and test) project with Maven
        if: "!contains(github.ref, 'renovate/major-quarkus')"
        run: mvn -B install --file pom.xml

  add-link:
    runs-on: ubuntu-latest
    needs: build-and-test
    #if: github.event_name == 'pull_request_target'
    steps:
      - name: Add link to Pull Request
        uses: redhat-actions/try-in-web-ide@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_comment: true
          web_ide_instance: https://this-is-ruhsis-test-url.com


