name: Build and Test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Echo github.ref
        run: echo ${{ github.ref }}

      - name: Break Build for branch 'renovate/major-quarkus*'
        if: contains(github.ref, 'postupgradetask/quarkus')
        run: mvn -B install '-Dtest=FailingTest' --file pom.xml

      - name: Build (and test) project with Maven
        if: "!contains(github.ref, 'postupgradetask/quarkus')"
        run: mvn -B install --file pom.xml

