name: PostUpgradeTask

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  postupgradetask:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.ref
        # renovate/maven-wrapper_3.1.1_3.3.2.x
        run: echo ${{ github.ref_name }}

      #- name: Parse branch name
      #  run: # TODO

      - uses: actions/checkout@v3
        name: checkout
        with:
          ref: main

      #- uses: peterjgrainger/action-create-branch@v2.2.0
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    branch: 'postupgradetask/' # TODO branch name

      - name: Upgrade
        run: echo hello world# TODO echo & touch (parsed depname, oldVersion, newVersion )