name: PostUpgradeTask Quarkus

on:
  push:
    branches:
      - 'renovate/quarkus**'

jobs:
  postupgradetask:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.ref
        run: echo ${{ github.ref_name }}

      - name: Parse branch name
        id: parse
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "DEPNAME=$(echo $BRANCH | cut -d'/' -f2 | cut -d'#' -f1)" >> "$GITHUB_OUTPUT"
          echo "CURR_VERSION=$(echo $BRANCH | cut -d'/' -f2 | cut -d'#' -f2)" >> "$GITHUB_OUTPUT"
          echo "NEW_VERSION=$(echo $BRANCH | cut -d'/' -f2 | cut -d'#' -f3)" >> "$GITHUB_OUTPUT"

      - name: echo parsed values
        env:
          DEPNAME: ${{ steps.parse.outputs.DEPNAME }}
          CURR_VERSION: ${{ steps.parse.outputs.CURR_VERSION }}
          NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
        run: echo "depname=${DEPNAME}, currVersion=${CURR_VERSION}, newVersion=${NEW_VERSION}"

      # TODO new branch from main? or from original renovate branch?
      - uses: actions/checkout@v3
        name: checkout
        with:
          ref: main

      # - name: Create branch
      #   env:
      #     DEPNAME: ${{ steps.parse.outputs.DEPNAME }}
      #     CURR_VERSION: ${{ steps.parse.outputs.CURR_VERSION }}
      #     NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
      #   run: |
      #     # TODO was wenn der branch schon existiert
      #     git checkout -B postupgradetask/${DEPNAME}#${CURR_VERSION}#${NEW_VERSION}
      #     git push --set-upstream origin postupgradetask/${DEPNAME}#${CURR_VERSION}#${NEW_VERSION}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Upgrade
        env:
          NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
        run: |
          ls -al
          ./mvnw -v
          java --version
          ./mvnw io.quarkus.platform:quarkus-maven-plugin:${NEW_VERSION}:update

      # - name: Push
      #   env:
      #     DEPNAME: ${{ steps.parse.outputs.DEPNAME }}
      #     CURR_VERSION: ${{ steps.parse.outputs.CURR_VERSION }}
      #     NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
      #   run: |
      #     git config --global user.email "postupgrade@anewhope.com"
      #     git config --global user.name "PostUpgradeTaskQuarkus"
      #     git add .
      #     git commit -m "updated ${DEPNAME} version from ${CURR_VERSION} to ${NEW_VERSION}"
      #     git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Upgrade quarkus from ${{ steps.parse.outputs.CURR_VERSION }} to ${{ steps.parse.outputs.NEW_VERSION }}
          branch: postupgradetask/${{ steps.parse.outputs.DEPNAME }}#${{ steps.parse.outputs.CURR_VERSION }}#${{ steps.parse.outputs.NEW_VERSION }}
          base: main