name: PostUpgradeTask Quarkus

on:
  push:
    branches:
      - 'renovate/**quarkus**'

jobs:
  postupgradetask:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.ref
        run: echo ${{ github.ref_name }}

      - name: Parse branch name
        id: parse
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          source update-info.txt

      - name: echo parsed values
        env:
          DEPNAME: ${{ steps.parse.outputs.DEPNAME }}
          CURR_VERSION: ${{ steps.parse.outputs.CURR_VERSION }}
          NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
        run: echo "depname=${DEPNAME}, currVersion=${CURR_VERSION}, newVersion=${NEW_VERSION}"

      - uses: actions/checkout@v3
        name: checkout
        with:
          ref: main

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Upgrade
        env:
          NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
        run: |
          ls -al
          ./mvnw -v
          java --version
          ./mvnw io.quarkus.platform:quarkus-maven-plugin:${NEW_VERSION}:update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Upgrade quarkus from ${{ steps.parse.outputs.CURR_VERSION }} to ${{ steps.parse.outputs.NEW_VERSION }}
          branch: postupgradetask/${{ steps.parse.outputs.DEPNAME }}#${{ steps.parse.outputs.CURR_VERSION }}#${{ steps.parse.outputs.NEW_VERSION }}
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          body: |
            Upgrade quarkus version
